dist: trusty

# Travis builds are slower using sudo: false (the container-based
# infrastructure) as of March 2017; see
# https://github.com/coq/coq/pull/467 for some discussion.
sudo: required

# Until Ocaml becomes a language, we set a known one.
language: c

cache:
  apt: true
  directories:
  - $HOME/.opam

before_cache:
  - rm -rf ~/.opam/log/

addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - gcc-multilib

env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  - CAMLP5_VER="6.14"
  - NATIVE_COMP="yes"
  - COQ_DEST="-local"
  # Main test suites
  matrix:
  - TEST_TARGET="test-suite" COMPILER="4.02.3+32bit"
  - TEST_TARGET="validate"                           TW="travis_wait"
  - TEST_TARGET="validate"   COMPILER="4.02.3+32bit" TW="travis_wait"
  - TEST_TARGET="ci-bignums TIMED=1"
  - TEST_TARGET="ci-color TIMED=1"
  - TEST_TARGET="ci-compcert TIMED=1"
  - TEST_TARGET="ci-coq-dpdgraph" EXTRA_OPAM="ocamlgraph"
  - TEST_TARGET="ci-coquelicot TIMED=1"
  - TEST_TARGET="ci-geocoq TIMED=1"
  - TEST_TARGET="ci-fiat-crypto TIMED=1"
  - TEST_TARGET="ci-fiat-parsers TIMED=1"
  - TEST_TARGET="ci-flocq TIMED=1"
  - TEST_TARGET="ci-formal-topology TIMED=1"
  - TEST_TARGET="ci-hott TIMED=1"
  - TEST_TARGET="ci-iris-coq TIMED=1"
  - TEST_TARGET="ci-math-classes TIMED=1"
  - TEST_TARGET="ci-math-comp TIMED=1"
  - TEST_TARGET="ci-sf TIMED=1"
  - TEST_TARGET="ci-unimath TIMED=1"
  - TEST_TARGET="ci-vst TIMED=1"
  # Not ready yet for 8.7
  # - TEST_TARGET="ci-cpdt TIMED=1"
  # - TEST_TARGET="ci-metacoq TIMED=1"
  # - TEST_TARGET="ci-tlc TIMED=1"

matrix:

  allow_failures:
  - env: TEST_TARGET="ci-coq-dpdgraph" EXTRA_OPAM="ocamlgraph"
  - env: TEST_TARGET="ci-geocoq TIMED=1"

  include:
    # Full Coq test-suite with two compilers
    - env:
      - TEST_TARGET="test-suite"
      - EXTRA_CONF="-coqide opt -with-doc yes"
      - EXTRA_OPAM="lablgtk-extras hevea"
      addons:
        apt:
          sources:
          - avsm
          packages: &extra-packages
          - opam
          - aspcud
          - libgtk2.0-dev
          - libgtksourceview2.0-dev
          - texlive-latex-base
          - texlive-latex-recommended
          - texlive-latex-extra
          - texlive-math-extra
          - texlive-fonts-recommended
          - texlive-fonts-extra
          - latex-xcolor
          - ghostscript
          - transfig
          - imagemagick
          - tipa

    - env:
      - TEST_TARGET="test-suite"
      - COMPILER="4.05.0"
      - CAMLP5_VER="7.01"
      - EXTRA_CONF="-coqide opt -with-doc yes"
      - EXTRA_OPAM="lablgtk-extras hevea"
      addons:
        apt:
          sources:
          - avsm
          packages: *extra-packages

    # Ocaml warnings with two compilers
    - env:
      - TEST_TARGET="coqocaml"
      - EXTRA_CONF="-coqide opt -warn-error"
      - EXTRA_OPAM="lablgtk-extras hevea"
      # dummy target
      - BUILD_TARGET="clean"
      addons:
        apt:
          sources:
          - avsm
          packages: &coqide-packages
          - opam
          - aspcud
          - libgtk2.0-dev
          - libgtksourceview2.0-dev

    - env:
      - TEST_TARGET="coqocaml"
      - COMPILER="4.05.0"
      - CAMLP5_VER="7.01"
      - EXTRA_CONF="-coqide opt -warn-error"
      - EXTRA_OPAM="lablgtk-extras hevea"
      # dummy target
      - BUILD_TARGET="clean"
      addons:
        apt:
          sources:
          - avsm
          packages: *coqide-packages

    - os: osx
      env:
      - TEST_TARGET="test-suite"
      - COMPILER="4.02.3"
      - CAMLP5_VER="6.17"
      - NATIVE_COMP="no"
      - COQ_DEST="-prefix _install"
      - EXTRA_CONF="-coqide opt -warn-error"
      - EXTRA_OPAM="lablgtk-extras"
      before_install:
      - brew update
      - brew install opam gnu-time gtk+ expat gtksourceview libxml2 gdk-pixbuf python3
      - pip3 install macpack
      before_deploy:
        - dev/build/osx/make-macos-dmg.sh
      deploy:
        provider: bintray
        user: maximedenes
        file: .bintray.json
        key:
          secure: "GDRjXPNvYHJBPMJqbXsSUAAPAZeGvr+mns80eYUD47Uxvueivql5VJ9d8MwLRJOV6lzwnQ1+F65WOKsR/JARMMRuVUKg3dAa3w1j8s2Yr/gwqsLt0G4Roqp93eTFDvs2X0xzzncN31G/NcV/5suc3oXuqjIF7EUSyrtiJUpMcIfFoMHWmdcGM9az4djIKYTzczAs+8MPSfrYD1AAqx2Ezeu+xDEmtvQ0w7OyO48ArUO4K5AWCRWdzSMN0A2s1w72fiCEfMgqzphzzJfRMPzp0rTF6/4CKRbtJpnSGtvovn2TeCRVDI8Y9k61nY5w5rR5Mcdf1K9BA1wzP2L4nTBoHbur70eMdEmeM3R2e9LzFETmuUAFh7L1k6LDhx7kFqjnSLwPSVa8ALK1bJDjgv1i300NCo5divaY/mjIr9e2/AZWL3MQjdwceoVZPrpCgKfpp44XdMYB/fi/wDLORQkLIm5fQMznDeYZKGceILRTwWyjL8Yyy+bBfA++frNLF8Agknfm0gGEI9VBaF7TVYbDJrZ2lmdT68D1hagJ8g1vief7HArTgapHfLxLL2BYWmapEm284GowHDrg4hGHd1aZu+wIh10SzPp4tTGRp0scu/x4ZEr7cglKgegwy9L7ubFA7zm9E368Y6RMxYXETBGgeEVDAqVnfBHIOZVvBIEgsCw="
          skip_cleanup: true
        on:
          all_branches: true

install:
- opam init -j ${NJOBS} --compiler=${COMPILER} -n -y
- eval $(opam config env)
- opam config list
- opam install -j ${NJOBS} -y camlp5.${CAMLP5_VER} ocamlfind ${EXTRA_OPAM}
- opam list

script:

- set -e
- echo 'Configuring Coq...' && echo -en 'travis_fold:start:coq.config\\r'
- ./configure ${COQ_DEST} -native-compiler ${NATIVE_COMP} ${EXTRA_CONF}
- echo -en 'travis_fold:end:coq.config\\r'

- echo 'Building Coq...' && echo -en 'travis_fold:start:coq.build\\r'
- make -j ${NJOBS}
- echo -en 'travis_fold:end:coq.build\\r'

- echo 'Running tests...' && echo -en 'travis_fold:start:coq.test\\r'
- ${TW} make -j ${NJOBS} ${TEST_TARGET}
- echo -en 'travis_fold:end:coq.test\\r'
- set +e

# Testing Gitter webhook
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3cdabdec318214c7cd63
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
