dist: trusty
language: ocaml
cache:
  apt: true
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - libgtk2.0-dev
    - libgtksourceview2.0-dev
    - texlive-latex-base
    - transfig
    - imagemagick
install:
- "[ -e .opam ] || opam init --compiler=4.02.3 -y"
- eval $(opam config env)
- opam config var root
- opam install -y camlp5 ocamlfind lablgtk-extras hevea
- opam list
script:
- ./configure -local -usecamlp5 -native-compiler yes -coqide opt -with-doc yes
- make
- travis_wait make validate
- travis_wait make test-suite
